version: '3.8'

services:
  
  # Web Server Service
  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
      - ui
      - db
    networks:
      - starter_networks

  #Database Service
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - starter_networks
  
  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    restart: always
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    links:
      - db:db
    depends_on:
      - db
    networks:
      - starter_networks

  # API Service 
  api:
    build:
      dockerfile: Dockerfile.api
    command: 'php artisan serve --host=0.0.0.0'
    container_name: ${PROJECT_NAME}-api
    volumes:
      - ./src/api:/var/www/api
      - /var/www/api/vendor
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - starter_networks

  # UI Service 
  ui:
    container_name: ${PROJECT_NAME}-ui
    build:
      dockerfile: Dockerfile.ui
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
    volumes:
      - ./src/ui:/var/www/ui
      - /var/www/ui/node_modules
      - /var/www/ui/.next
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - starter_networks
networks:
  starter_networks: